# Generated by Django 2.1.15 on 2020-09-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainDirectory',
            fields=[
                ('domain_directory_sid', models.AutoField(primary_key=True, serialize=False)),
                ('domain_directory_id', models.CharField(max_length=30)),
                ('domain_directory_name', models.CharField(max_length=255)),
                ('domain_directory_desc', models.CharField(blank=True, max_length=4000, null=True)),
                ('domain_directory_type', models.CharField(blank=True, max_length=30, null=True)),
                ('domain_directory_status', models.CharField(max_length=30)),
                ('insert_date', models.DateTimeField(null=True)),
                ('insert_user', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'domain_directory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DomainValue',
            fields=[
                ('domain_value_sid', models.AutoField(primary_key=True, serialize=False)),
                ('domain_value_value', models.CharField(max_length=30)),
                ('domain_value_desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('domain_value_data_type', models.CharField(blank=True, max_length=30, null=True)),
                ('domain_value_status', models.CharField(max_length=30)),
                ('insert_date', models.DateTimeField(null=True)),
                ('insert_user', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'domain_value',
                'managed': False,
            },
        ),
    ]
