name: praksa
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - openssl=1.1.1g
  - pip=20.2.2
  - python=3.7.7
  - setuptools=49.6.0
  - sqlite=3.33.0
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.34.2
  - wincertstore=0.2
  - zlib=1.2.11
  - pip:
    - asgiref==3.2.10
    - chardet==3.0.4
    - colorama==0.4.3
    - django==2.1.15
    - django-cors-headers==2.4.1
    - django-pyodbc==1.1.3
    - django-pyodbc-azure==2.1.0.0
    - djangorestframework==3.11.1
    - idna==2.10
    - importlib-metadata==1.7.0
    - pyodbc==4.0.30
    - pytz==2020.1
    - requests==2.24.0
    - sqlparse==0.3.1
    - urllib3==1.25.10
    - zipp==3.1.0
