export class Batch {
    batch_sid; 
    datasource_sid?; 
    batch_id?; 
    batch_name?; 
    batch_desc?; 
    batch_type?; 
    batch_status?; 
    server_name?; 
    source_database_name?; 
    destination_database_name?; 
    ssis_package_name?; 
    job_name?; 
    job_step_name?; 
    job_scheduled?;
    dashboard_type?; 
    use_mail_status?; 
    insert_date?; 
    insert_user?; 
    update_date?; 
    update_user?; 
    datasource_name?; 
}
